import re
import numpy
from statsmodels import robust

f = open('zoo.data')
Hair = []
Feather = []
Eggs = []
Milk = []
Airborne = []
Aquatic = []
Predator = []
Toothed = []
Backbone = []
Breathes = []
Venomous = []
Fins = []
Legs = []
Tail = []
Domestic = []
Catsize = []
Type = []

temp = ""

for line in f:
    temp = line

    a = re.findall('\d+', temp)

    Hair.append(int(a[0]))
    Feather.append(int(a[1]))
    Eggs.append(int(a[2]))
    Milk.append(int(a[3]))
    Airborne.append(int(a[4]))
    Aquatic.append(int(a[5]))
    Predator.append(int(a[6]))
    Toothed.append(int(a[7]))
    Backbone.append(int(a[8]))
    Breathes.append(int(a[9]))
    Venomous.append(int(a[10]))
    Fins.append(int(a[11]))
    Legs.append(int(a[12]))
    Tail.append(int(a[13]))
    Domestic.append(int(a[14]))
    Catsize.append(int(a[15]))
    Type.append(int(a[16]))

print('Mean:')
print('Hair:', numpy.mean(Hair))
print('Feather:', numpy.mean(Feather))
print('Eggs:', numpy.mean(Eggs))
print('Milk:', numpy.mean(Milk))
print('Airbone:', numpy.mean(Airborne))
print('Aquatic:', numpy.mean(Aquatic))
print('Predator:', numpy.mean(Predator))
print('Toothed:', numpy.mean(Toothed))
print('Backbone:', numpy.mean(Backbone))
print('Breathes:', numpy.mean(Breathes))
print('Venomous:', numpy.mean(Venomous))
print('Fins:', numpy.mean(Fins))
print('Legs:', numpy.mean(Legs))
print('Tail:', numpy.mean(Tail))
print('Domestic:', numpy.mean(Domestic))
print('Catsize:', numpy.mean(Catsize))
print('Type:', numpy.mean(Type))
print('\n')
print('Median:')
print('Hair:', numpy.median(Hair))
print('Feather:', numpy.median(Feather))
print('Eggs:', numpy.median(Eggs))
print('Milk:', numpy.median(Milk))
print('Airbone:', numpy.median(Airborne))
print('Aquatic:', numpy.median(Aquatic))
print('Predator:', numpy.median(Predator))
print('Toothed:', numpy.median(Toothed))
print('Backbone:', numpy.median(Backbone))
print('Breathes:', numpy.median(Breathes))
print('Venomous:', numpy.median(Venomous))
print('Fins:', numpy.median(Fins))
print('Legs:', numpy.median(Legs))
print('Tail:', numpy.median(Tail))
print('Domestic:', numpy.median(Domestic))
print('Catsize:', numpy.median(Catsize))
print('Type:', numpy.median(Type))
print('\n')
print('MAD:')
print('Hair:', robust.mad(Hair))
print('Feather:', robust.mad(Feather))
print('Eggs:', robust.mad(Eggs))
print('Milk:', robust.mad(Milk))
print('Airbone:', robust.mad(Airborne))
print('Aquatic:', robust.mad(Aquatic))
print('Predator:', robust.mad(Predator))
print('Toothed:', robust.mad(Toothed))
print('Backbone:', robust.mad(Backbone))
print('Breathes:', robust.mad(Breathes))
print('Venomous:', robust.mad(Venomous))
print('Fins:', robust.mad(Fins))
print('Legs:', robust.mad(Legs))
print('Tail:', robust.mad(Tail))
print('Domestic:', robust.mad(Domestic))
print('Catsize:', robust.mad(Catsize))
print('Type:', robust.mad(Type))
print('\n')
print('Standard Deviation:')
print('Hair:', numpy.std(Hair))
print('Feather:', numpy.std(Feather))
print('Eggs:', numpy.std(Eggs))
print('Milk:', numpy.std(Milk))
print('Airbone:', numpy.std(Airborne))
print('Aquatic:', numpy.std(Aquatic))
print('Predator:', numpy.std(Predator))
print('Toothed:', numpy.std(Toothed))
print('Backbone:', numpy.std(Backbone))
print('Breathes:', numpy.std(Breathes))
print('Venomous:', numpy.std(Venomous))
print('Fins:', numpy.std(Fins))
print('Legs:', numpy.std(Legs))
print('Tail:', numpy.std(Tail))
print('Domestic:', numpy.std(Domestic))
print('Catsize:', numpy.std(Catsize))
print('Type:', numpy.std(Type))
print('\n')
print('Variance:')
print('Hair:', numpy.var(Hair))
print('Feather:', numpy.var(Feather))
print('Eggs:', numpy.var(Eggs))
print('Milk:', numpy.var(Milk))
print('Airbone:', numpy.var(Airborne))
print('Aquatic:', numpy.var(Aquatic))
print('Predator:', numpy.var(Predator))
print('Toothed:', numpy.var(Toothed))
print('Backbone:', numpy.var(Backbone))
print('Breathes:', numpy.var(Breathes))
print('Venomous:', numpy.var(Venomous))
print('Fins:', numpy.var(Fins))
print('Legs:', numpy.var(Legs))
print('Tail:', numpy.var(Tail))
print('Domestic:', numpy.var(Domestic))
print('Catsize:', numpy.var(Catsize))
print('Type:', numpy.var(Type))
print('\n')
print('Max:')
print('Hair:', numpy.max(Hair))
print('Feather:', numpy.max(Feather))
print('Eggs:', numpy.max(Eggs))
print('Milk:', numpy.max(Milk))
print('Airbone:', numpy.max(Airborne))
print('Aquatic:', numpy.max(Aquatic))
print('Predator:', numpy.max(Predator))
print('Toothed:', numpy.max(Toothed))
print('Backbone:', numpy.max(Backbone))
print('Breathes:', numpy.max(Breathes))
print('Venomous:', numpy.max(Venomous))
print('Fins:', numpy.max(Fins))
print('Legs:', numpy.max(Legs))
print('Tail:', numpy.max(Tail))
print('Domestic:', numpy.max(Domestic))
print('Catsize:', numpy.max(Catsize))
print('Type:', numpy.max(Type))
print('\n')
print('Min:')
print('Hair:', numpy.min(Hair))
print('Feather:', numpy.min(Feather))
print('Eggs:', numpy.min(Eggs))
print('Milk:', numpy.min(Milk))
print('Airbone:', numpy.min(Airborne))
print('Aquatic:', numpy.min(Aquatic))
print('Predator:', numpy.min(Predator))
print('Toothed:', numpy.min(Toothed))
print('Backbone:', numpy.min(Backbone))
print('Breathes:', numpy.min(Breathes))
print('Venomous:', numpy.min(Venomous))
print('Fins:', numpy.min(Fins))
print('Legs:', numpy.min(Legs))
print('Tail:', numpy.min(Tail))
print('Domestic:', numpy.min(Domestic))
print('Catsize:', numpy.min(Catsize))
print('Type:', numpy.min(Type))

f.close()